# Generated by Django 4.1.2 on 2022-10-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('cost', models.IntegerField()),
                ('service', models.IntegerField()),
                ('picture', models.ImageField(blank=True, upload_to='pictures/%Y/%M/%D/')),
            ],
        ),
    ]
