# Generated by Django 4.1.2 on 2022-10-11 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(db_index=True, max_length=150)),
            ],
            options={
                'verbose_name': 'Кузов',
                'verbose_name_plural': 'Кузов автомобиля',
            },
        ),
        migrations.AddField(
            model_name='cars',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Cars.types'),
        ),
    ]
