# Generated by Django 4.1.2 on 2022-10-11 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0002_types_cars_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(db_index=True, max_length=150, verbose_name='Местность')),
            ],
            options={
                'verbose_name': 'Местность',
                'verbose_name_plural': 'Вид местности',
            },
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel', models.CharField(db_index=True, max_length=150, verbose_name='Топливо')),
            ],
            options={
                'verbose_name': 'Топливо',
                'verbose_name_plural': 'Вид топлива',
            },
        ),
        migrations.AddField(
            model_name='cars',
            name='carmod',
            field=models.CharField(default=2, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='types',
            name='type',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Кузов'),
        ),
        migrations.AddField(
            model_name='cars',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Cars.country'),
        ),
        migrations.AddField(
            model_name='cars',
            name='fuel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Cars.fuel'),
        ),
    ]
